language: php
php:
  - '8.2'

before_script:
  - rm -rf composer.lock
  - composer install

script:
  -mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls
  - travis_retry php vendor/bin/coveralls -v
