language: php

php:
  - 8.0

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
